kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: cm9vdA==
  password: UEBzc3cwcmQ=
---
kind: Pod
apiVersion: v1
metadata:
  name: mysql-server
  labels:
    role: server
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
    ports:
    - containerPort: 3036
---
kind: Pod
apiVersion: v1
metadata:
  name: mysql-client
  labels:
    role: client
spec:
  containers:
  - name: client
    image: mysql
    lifecycle:
      postStart:
        exec:
          command: [ "bin/bash", "-c", "apt update && apt install -y git" ]
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
---
